from .. import data_types as dt


others: list[dt.ControlJsonScheme] = [
    dt.ControlJsonScheme(
        name="animation.implicit",
        source="flet_core.animation",
        attr="implicit",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="Option",
        source="flet_core.dropdown",
        attr="Option",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="BorderSide",
        source="flet_core.border",
        attr="BorderSide",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="color.with_opacity",
        source="flet_core.colors",
        attr="with_opacity",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="margin.symmetric",
        source="flet_core.margin",
        attr="symmetric",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="margin.all",
        source="flet_core.margin",
        attr="all",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="margin.only",
        source="flet_core.margin",
        attr="only",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="padding.symmetric",
        source="flet_core.padding",
        attr="symmetric",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="padding.all",
        source="flet_core.padding",
        attr="all",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="padding.only",
        source="flet_core.padding",
        attr="only",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border.symmetric",
        source="flet_core.border",
        attr="symmetric",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border.all",
        source="flet_core.border",
        attr="all",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border.only",
        source="flet_core.border",
        attr="only",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="BorderSide",
        source="flet_core.border",
        attr="BorderSide",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border_radius.horizontal",
        source="flet_core.border_radius",
        attr="horizontal",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border_radius.vertical",
        source="flet_core.border_radius",
        attr="vertical",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border_radius.all",
        source="flet_core.border_radius",
        attr="all",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="border_radius.only",
        source="flet_core.border_radius",
        attr="only",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.bottom_center",
        source="flet_core.alignment",
        attr="bottom_center",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.bottom_left",
        source="flet_core.alignment",
        attr="bottom_left",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.bottom_right",
        source="flet_core.alignment",
        attr="bottom_right",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.center",
        source="flet_core.alignment",
        attr="center",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.center_right",
        source="flet_core.alignment",
        attr="center_right",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.center_left",
        source="flet_core.alignment",
        attr="center_left",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.top_center",
        source="flet_core.alignment",
        attr="top_center",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.top_left",
        source="flet_core.alignment",
        attr="top_left",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="alignment.top_right",
        source="flet_core.alignment",
        attr="top_right",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="MatplotlibChart",
        source="flet.matplotlib_chart",
        attr="MatplotlibChart",
        is_awaitable=False
    ),
    dt.ControlJsonScheme(
        name="PlotlyChart",
        source="flet.plotly_chart",
        attr="PlotlyChart",
        is_awaitable=False
    )
]
